# Site settings
title: 樊凡's Blog 
header-img: img/home-bg.jpg
email: 792924802@qq.com
description: "学生党，IOS开发爱好者"
baseurl: ""
url: "http://misszf.github.io/misszf/"
twitter_username: misszf
github_username:  misszf
facebook_username:  misszf
weibo_username: misszf
zhihu_username: misszf

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
