# Site settings
title: 樊凡's Blog 
header-img: img/home-bg.jpg
email: 545227212@qq.com
description: "学生党，IOS开发爱好者"
baseurl: ""
url: "http://zfha.github.io"
twitter_username: zfha
github_username:  zfha
facebook_username:  zfha
weibo_username: zfha
zhihu_username: zfha

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
